osx_image: xcode8.3
sudo: required
dist: trusty
language: c
matrix:
  include:
  - os: osx
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
addons:
  apt:
    packages:
    - libgnome-keyring-dev
    - icnsutils
before_install:
- mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v1.2.1/git-lfs-$([
  "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-1.2.1.tar.gz
  | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --no-install-recommends
  -y icnsutils graphicsmagick xz-utils; fi
install:
- nvm install 8
- curl -o- -L https://yarnpkg.com/install.sh | bash
- source ~/.bashrc
- npm install -g xvfb-maybe
- yarn
script:
- yarn run build
branches:
  only:
  - master
deploy:
  provider: releases
  api_key:
    secure: am6cNOgo+gEaepegy+wKShy4LkBD9044pM0KUFv8EyDVumwx0/KkOIRxTmjGMpIsDbRvlxf7upNEqnu18ssNb1nqp8zFYuD1jsqOxG4w27kVd0MYoNZXhPsGxYBBjuXNMSirkRnjuT6gtusPdhw3gm5VSZhcAK96Z7V7aabFbgHrm9aMAnnbxlAlN0q+dqRtxX4zbBUmRnPdoWXnZ/ysZ/cDopl2wSvKvhVz7Oukf4XRB3s4SqlDLRXzCtl0OA8RwoqnMiBlTOImDfFOohd2fbW+uQ6TGom2LMjmTgAdM4/rEgsTNOExZdCjDhi6douGZtPFLt+BvwyJI9X5bcVxQEX6nAZM0d6bRumtDI1CrcGbquJCMX564gt+fWHyRfXeCtcISXKK3/RrYTkVB8Ibd9BVyxcxf4eXgz17pmTeJc6YnKS0CAG3I32WdKnPWDOdBm4YyWYKZjCvDzguN2ds5rMu/b8NbebjwAiWmJqOcTo7B4LMRfXafdvsMXd81YhhsmUflgzV8Mer4aTz3m4cvEkeO4ZIlgC5RuPx4pNL8QzQcJzvxEgZErr8BE0e41bbvZlR6lDCPpHXFIrXV29qHEcS9G6PMZSLrtKPZEYV/AqVkVVnZEq9PNR9TrRHQL3relVBTZrFtOWkZAYaaL50pupBK13oEkjYpA1sMhyMFeQ=
  file: build/mmb-electron-0.0.1.dmg
  skip_cleanup: true
  draft: true
  on:
    repo: IMFS-MMB/mmb-gui-electron

