env:
  - SFTP_PASSWORD
      secure: "o7z6tkn6JR4/qnQc43nHx0kSlEXt4IIpCT5MMjv0BBwqpo6KzP3m2GtbAhO1YpXdWVrIXa/6x+mdFSuq7mGom/Rv9HR0xQho1/ScNvtZc7xiuSCbAc3mifWFlhledeYGD5m/vcGoHPUKmQbhzxVmpLqvedTu5eLNm2nO0xrS/6EN4wbezxH5jhBRbvXk4IWzA3xbg79ClBF8M9uJoMjE2ILnFfkwBo2giRji9ZEVqN8nylbeZjsdHl//nrP6mZn+novh4rPqy0V1mUW1JxDDFXeBWJPtQIZjYvhW/4+vGL6XdfSTp+WRhRcIizRzZSIAKJ0IBbkySPR6SdsWw5HvmK3l0AVyzsJonPRVXoNiCOVTWm0Iyt5wMPEA769YM9tSwdq3M8nTnKXmK/DXutJZzMCI0IqOTVD3IMpyUFcMpGhQbpCkzB3VDLpJdEUVI0wXhGg0h0EPg0rN5NGmaVVtvvBmz9EHay7KL9jLBSI1RSPpsQ2ZrNwa78WLpyJcYUCB+28svdZBPRR/1z+2c1odUXivHWxjWzc9iVLE16MRRsJFd9kNhexZ3wxsjGbjna4axGhFQFu9x701jjVCD1pOxFenbO5Zrlowi867G5gzsvpDe7F2cJP7O+bBGLnAzRx6WwSdknG8nLHJuR5KNCO5V4+rxFIBD1vP1/FtaE6N6fM="

osx_image: xcode8.3
sudo: required
dist: trusty
language: c
matrix:
  include:
  - os: osx
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
addons:
  apt:
    packages:
    - libgnome-keyring-dev
    - icnsutils
before_install:
- mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v1.2.1/git-lfs-$([
  "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-1.2.1.tar.gz
  | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --no-install-recommends
  -y icnsutils graphicsmagick xz-utils; fi
install:
- nvm install 8
- source ~/.bashrc
- npm install -g xvfb-maybe
- npm install
script:
- npm run build
branches:
  only:
  - master

after_success:
  - node .scripts/deploy.js
