version: 0.1.{build}

branches:
  only:
    - master

image: Visual Studio 2017
platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\AppData\Local\Yarn\cache'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - git reset --hard HEAD
  - npm install
  - node --version

build_script:
  - npm run build
  - npm run build:web

after_build:
  - 7z a web.zip dist/web/

test: off

artifacts:
  - path: build/*.exe
    name: BuildWin
  - path: web.zip
    name: BuildWeb

deploy:
  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: 'Release description'
    auth_token:
      secure: Umyb8lnZeivbvN4AoqdXEhoFbP9trQybmA6pUJ+pY6xh0D+n6iEzZW0ol3brZR0B
    artifact: BuildWin
    draft: true
    prerelease: false
    on:
      branch: master
      APPVEYOR_REPO_TAG: true
