version: 0.1.{build}

branches:
  only:
    - master

image: Visual Studio 2017
platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\AppData\Local\Yarn\cache'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - git reset --hard HEAD
  - npm install
  - node --version

build_script:
  - npm run build
  - npm run build:web

after_build:
  - 7z a web.zip dist/web/

test: off

artifacts:
  - path: build/*.exe
    name: BuildWin
  - path: web.zip
    name: BuildWeb

deploy:
  - provider: FTP
    protocol: sftp
    host: macromodelbase.com:2222
    username: deploy
    password:
      secure: Jk84+PZDSf/7XPb9gd8vvbjsh2SGSpPIhwVDjSBfSx0=
    folder: data/mmb-electron-latest
    artifact: BuildWin
    on:
      branch: master
